openapi: 3.0.0
info:
  title: Social App
  description: our first Social app at LCO Saleh
  version: 1.0.1

servers:
  - url: http://localhost:4000/api/v1
    description: localhost version our App
  - url: https://localhost:4000/api/v1
    description: this is a dummy api URL, it doesn't work


components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer


paths:
  /instagram:
    get:
      tags:
        - Get
      summary: return usename, followers and follows
      responses: 
        '200': # status code
          description: returns an object
          content: 
            application/json:
              schema:
                type: object
                properties: 
                  username:
                    type: string
                  followers:
                    type: string
                  followes:
                    type: string
    post:
      tags:
        - post
      summary: return usename, followers and follows
      responses: 
        '200': # status code
          description: returns an object
          content: 
            application/json:
              schema:
                type: object
                properties: 
                  username:
                    type: string
                  followers:
                    type: string
                  followes:
   
                    type: string
                    
  /facebook:
    get:
      tags:
        - Get
      summary: return usename, followers and follows
      responses: 
        '200': # status code
          description: returns an object
          content: 
            application/json:
              schema:
                type: object
                properties: 
                  username:
                    type: string
                  followers:
                    type: string
                  followes:
                    type: string
    post:
      tags:
        - post
      summary: return usename, followers and follows
      responses: 
        '200': # status code
          description: returns an object
          content: 
            application/json:
              schema:
                type: object
                properties: 
                  username:
                    type: string
                  followers:
                    type: string
                  followes:
   
                    type: string


  /linkedin:
    get:
      tags:
        - Get
      summary: Returns usename, Followers & Follows.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: object
                properties:
                  username:
                    type: string
                  course:
                    type: string
                  price:
                    type: number
        400:
          description: Request failing
        500:
          description: Service Down
    post:
      tags:
        - post
      summary: return usename, followers and follows
      responses: 
        200:
          description: returns an object
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  course:
                    type: string
                  price:
                    type: number
        400:
          description: bad Request        
        500:
          description: Serveice Down


  /{anything}:
    get:
      tags:
        - Get
      summary: return whatever is in the URL parameter
      parameters: 
        - name: anything
          default: 11
          in: path 
          schema:
            type: string
      responses: 
        '200': # status code
          description: returns an object
          content: 
            application/json:
              schema:
                type: object
                properties: 
                  params:
                    type: string
